[build]
  command = "yarn run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  external_node_modules = [
    "a11y-mcp-server",
    "@modelcontextprotocol/sdk"
  ]
  included_files = [
    "node_modules/.bin/a11y-mcp-server",
    "node_modules/a11y-mcp-server/**"
  ]

[build.environment]
  NODE_VERSION = "18"
