export default function SiteFooter() {
  return (
    <footer className="bg-ample-gray backdrop-blur mt-16">
      <div className="mx-auto max-w-8xl px-6 py-6">
        <div className="text-center">
          <p className="text-sm text-slate-400">
            This free website audit was generated by {` `}
            <a
              href="https://ample.co"
              target="_blank"
              rel="noopener noreferrer"
              className="text-slate-200 hover:text-orange-400 transition-colors underline decoration-slate-600 hover:decoration-orange-400 underline-offset-2"
            >
              Ample
            </a>.
          </p>
        </div>
      </div>
    </footer>
  );
}